# Generated by Django 4.2.20 on 2025-06-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curral', '0001_initial'),
        ('lote', '0001_initial'),
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoloteorigem',
            name='curral',
        ),
        migrations.RemoveField(
            model_name='movimentacaoloteorigem',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='movimentacaoloteorigem',
            name='movimentacao',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='curral_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_curral_destino', to='curral.curral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='lote_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='lote.lote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='lote_origem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='lote.lote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_movimentacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='idmovimentacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='movimentacao.statusmovimentacao'),
        ),
        migrations.AlterField(
            model_name='statusmovimentacao',
            name='idstatus_movimentacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statusmovimentacao',
            name='nome_status',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='MovimentacaoLoteDestino',
        ),
        migrations.DeleteModel(
            name='MovimentacaoLoteOrigem',
        ),
    ]
