# Generated by Django 4.2.20 on 2025-06-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejo', '0004_alter_boimanejo_idboi_manejo_alter_manejo_idmanejo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manejo',
            name='status_manejo',
            field=models.ForeignKey(help_text='Status atual do manejo: Aberto ou Finalizado.', on_delete=django.db.models.deletion.PROTECT, related_name='manejos_por_status', to='manejo.statusmanejo'),
        ),
        migrations.AlterField(
            model_name='manejo',
            name='tipo_manejo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Movimentacao', 'Movimentação'), ('Venda', 'Venda')], default='Entrada', help_text='Tipo de manejo aplicado: Entrada, Movimentação ou Venda.', max_length=15),
        ),
        migrations.DeleteModel(
            name='TipoManejo',
        ),
    ]
